/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static
#ifdef G_HAVE_INLINE
inline
#endif
void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_org_gtk_UniqueApp
#define DBUS_GLIB_CLIENT_WRAPPERS_org_gtk_UniqueApp

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_gtk_UniqueApp_send_message (DBusGProxy *proxy, const char * IN_command, const GValueArray* IN_message, const guint IN_time, char ** OUT_response, GError **error)

{
  return dbus_g_proxy_call (proxy, "SendMessage", error, G_TYPE_STRING, IN_command, dbus_g_type_get_struct ("GValueArray", G_TYPE_STRING, G_TYPE_UINT, G_TYPE_UINT, G_TYPE_UINT, G_TYPE_STRING, G_TYPE_INVALID), IN_message, G_TYPE_UINT, IN_time, G_TYPE_INVALID, G_TYPE_STRING, OUT_response, G_TYPE_INVALID);
}

typedef void (*org_gtk_UniqueApp_send_message_reply) (DBusGProxy *proxy, char * OUT_response, GError *error, gpointer userdata);

static void
org_gtk_UniqueApp_send_message_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  char * OUT_response;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_STRING, &OUT_response, G_TYPE_INVALID);
  (*(org_gtk_UniqueApp_send_message_reply)data->cb) (proxy, OUT_response, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_gtk_UniqueApp_send_message_async (DBusGProxy *proxy, const char * IN_command, const GValueArray* IN_message, const guint IN_time, org_gtk_UniqueApp_send_message_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "SendMessage", org_gtk_UniqueApp_send_message_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_STRING, IN_command, dbus_g_type_get_struct ("GValueArray", G_TYPE_STRING, G_TYPE_UINT, G_TYPE_UINT, G_TYPE_UINT, G_TYPE_STRING, G_TYPE_INVALID), IN_message, G_TYPE_UINT, IN_time, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_org_gtk_UniqueApp */

G_END_DECLS
